[package]
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
edition = "2018"
name = "tcptunnel"
version = "0.1.0"
license = "GPL-2.0-or-later"

[dependencies]
bytes = "0.4.12"
tokio = "0.1.21"
structopt = "0.2"
anyhow = "1.0"
